### ISSUE TITLE
[NativeScript/nativescript-ui-charts] [IOS] [NS 8.5.3] Color and dataLabels are not displayed on IOS

### ISSUE THREAD

**Issue by vicmasa** [NativeScript/ui-kit#1]
Hello everyone.

Case 1: When testing the donut graph, detailed in the example [here](https://github.com/NativeScript/ui-kit/blob/main/apps/demo/src/chart-demos/3d-charts/3d-donut/3d-donut-page.ts), it works correctly on Android, but on IOS, the colors are not displayed, attach project in github [here](https://github.com/vicmasa/ns853). See image 1

<img width="402" alt="image" src="https://user-images.githubusercontent.com/34837622/236075011-646960b5-71c9-4adc-9d36-93512e3c9043.png">

Case 2: When other detailed configuration is used in this jsfddle example [here](https://jsfiddle.net/bo9djtxs/) (correct example), it displays colors correctly on IOS, but the dataLabels parameter, doesn't work correctly. See image 2

<img width="410" alt="Captura de pantalla 2023-05-03 a la(s) 18 43 43" src="https://user-images.githubusercontent.com/34837622/236074572-fcd04352-5e7a-4ace-a188-343f1b6e6ff2.png">

Note: In android its ok all

Thanks for your help.

```yaml
OS: macOS 13.3.1
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 19.8.1
npm: 9.5.1
nativescript: 8.5.3

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.3/14E222b
cocoapods: 1.12.1
python: 2.7.18
python3: 3.9.6
ruby: 2.7.8
platforms: 
  - DriverKit 22.4
  - iOS 16.4
  - macOS 13.3
  - tvOS 16.4
  - watchOS 9.4
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.5.0",
  "@nativescript/theme": "~3.0.2",
  "@nativescript/ui-charts": "^0.4.0"
},
"devDependencies": {
  "@nativescript/android": "8.5.0",
  "@nativescript/ios": "8.5.1",
  "@nativescript/webpack": "~5.0.14"
}
```
